### PR TITLE
Fix #89

### LINKED ISSUE #89: https://www.youtube.com/watch/dQw4w9WgXcQ
**Describe the bug**  
URLs in the format https://www.youtube.com/watch/dQw4w9WgXcQ aren't recognized.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Call `getVideoId` with the url string "https://www.youtube.com/watch/dQw4w9WgXcQ"
2. returns `{ id: undefined, service: 'youtube' }`

**Expected behavior**  
returns `{ id: 'dQw4w9WgXcQ', service: 'youtube' }`

**Environment**  
I can repro anywhere.

**Module version**  
The version of `get-video-id` where I am experiencing this problem is `v3.5.3`

### PR DESCRIPTION
**Pull request by easrng**
Adds support for URLs like https://www.youtube.com/watch/dQw4w9WgXcQ

### CODE REVIEW

File: src/youtube.js [hunk 1]
```diff
@@ -8,15 +8,15 @@
...
 	}
 
 	if (shortcodeString.includes('/')) {
-		return shortcodeString.split('/')[0];
+		shortcodeString = shortcodeString.split('/')[0];
 	}
 
 	if (shortcodeString.includes('&')) {
-		return shortcodeString.split('&')[0];
+		shortcodeString = shortcodeString.split('&')[0];
```
Comment (radiovisual) [inline src/youtube.js:19]: Curious: why did you make these changes? They seem to be unrelated to the PR, plus I prefer to let the function return as soon as it finds what it needs, so that it doesn't still have to do all these unnecessary checks.

**Review by radiovisual — CHANGES_REQUESTED** [review]
Cool! thanks for your help. Somehow we managed to miss this popular format! Nice catch! I just have one nitpicky change request, otherwise it looks good to me

**Comment by easrng** [comment]
I had to change that to allow for videos with a trailing slash I think.

IIRC before if you gave it a value like "something/?source=whatever" it would only strip off the query string and not the slash.

**Comment by radiovisual** [comment]
> I had to change that to allow for videos with a trailing slash I think. IIRC before if you gave it a value like "something/?source=whatever" it would only strip off the query string and not the slash.

Interesting. I see what you mean. I guess that routine might be a bit fragile then, since if we change the order of those `if` statements then some patterns might fail, but if it works for now, then let's leave it as-is in this PR and I will take a look at the function later on to make it bit safer to use/maintain.

**Review by radiovisual — APPROVED** [review]

**Comment by radiovisual** [comment]
Thanks again! I will merge this and get it published in the next version.
